// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgcruiocwuphudimypiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnY3J1aW9jd3VwaHVkaW15cGlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDg3NTMsImV4cCI6MjA2NjYyNDc1M30.c9-u8lLeTfPYYxEvveO0xCzTy7X2lRuh_SZOALko9pM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);